mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: petmily.domain

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: petmily
    password: petmily
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  messages:
    basename: errors