mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: petmily.domain

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: petmily
    password: petmily
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  mail:
    host: smtp.naver.com
    port: 465
    username: 계정
    password: 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          ssl:
            trust: smtp.naver.com
            enable: true