-- DDL

-- 유기동물
CREATE TABLE ABANDONEDANIMAL (
	ABNUMBER NUMBER NOT NULL,
	SNUMBER NUMBER DEFAULT 0 NOT NULL,
	NAME VARCHAR2(30) DEFAULT '미정' NOT NULL,
	SPECIES VARCHAR2(10) DEFAULT '기타' NOT NULL,
	KIND VARCHAR2(50) NULL,
	GENDER CHAR(1) DEFAULT '-' NOT NULL,
	AGE NUMBER NULL,
	WEIGHT FLOAT NULL,
	IMGPATH VARCHAR2(300) DEFAULT 'no_image.png' NULL,
	LOCATION VARCHAR2(50) NULL,
	ADMISSIONDATE DATE NOT NULL,
	UNIQUENESS VARCHAR2(100) NULL,
	DESCRIPTION VARCHAR2(100) NULL,
	ANIMALSTATE VARCHAR2(10) DEFAULT '보호' NOT NULL,
	CONSTRAINT AB_GENDER_CHECK CHECK (gender IN ('F', 'M', '-')),
	CONSTRAINT AB_SPECIES_CHECK CHECK (species IN ('개', '고양이', '기타')),
	CONSTRAINT AB_STATE_CHECK CHECK (animalstate IN ('보호','입양','임보')),
	CONSTRAINT PK_ABANDONEDANIMAL PRIMARY KEY (ABNUMBER),
	CONSTRAINT AB_CK_ABNUMBER_NOTNULL CHECK ("ABNUMBER" IS NOT NULL),
	CONSTRAINT AB_CK_SNUMBER_NOTNULL CHECK ("SNUMBER" IS NOT NULL),
	CONSTRAINT AB_CK_NAME_NOTNULL CHECK ("NAME" IS NOT NULL),
	CONSTRAINT AB_CK_SPECIES_NOTNULL CHECK ("SPECIES" IS NOT NULL),
	CONSTRAINT AB_CK_GENDER_NOTNULL CHECK ("GENDER" IS NOT NULL),
	CONSTRAINT AB_CK_ADMISSIONDATE_NOTNULL CHECK ("ADMISSIONDATE" IS NOT NULL),
	CONSTRAINT AB_CK_ANIMALSTATE_NOTNULL CHECK ("ANIMALSTATE" IS NOT NULL)
);

COMMENT ON TABLE AbandonedAnimal IS '유기동물';
COMMENT ON COLUMN AbandonedAnimal.abNumber IS '유기동물 번호';
COMMENT ON COLUMN AbandonedAnimal.sNumber IS '보호소 번호';
COMMENT ON COLUMN AbandonedAnimal.name IS '이름';
COMMENT ON COLUMN AbandonedAnimal.species IS '종';
COMMENT ON COLUMN AbandonedAnimal.kind IS '품종';
COMMENT ON COLUMN AbandonedAnimal.gender IS '성별';
COMMENT ON COLUMN AbandonedAnimal.age IS '나이';
COMMENT ON COLUMN AbandonedAnimal.weight IS '체중';
COMMENT ON COLUMN AbandonedAnimal.imgPath IS '사진';
COMMENT ON COLUMN AbandonedAnimal.location IS '지역';
COMMENT ON COLUMN AbandonedAnimal.admissionDate IS '입소 날짜';
COMMENT ON COLUMN AbandonedAnimal.uniqueness IS '특이사항';
COMMENT ON COLUMN AbandonedAnimal.description IS '소개글';
COMMENT ON COLUMN AbandonedAnimal.animalState IS '유기동물 상태';

-- 입양
CREATE TABLE ADOPT (
	ADNUMBER NUMBER NOT NULL,
    ABNUMBER NUMBER NOT NULL,
	MNUMBER NUMBER NOT NULL,
	RESIDENCE VARCHAR2(30) NOT NULL,
	MARITALSTATUS VARCHAR2(30) NOT NULL,
	JOB VARCHAR2(50) NOT NULL,
	STATUS VARCHAR2(10) DEFAULT '처리중' NOT NULL,
	CONSTRAINT PK_ADOPT PRIMARY KEY (ADNUMBER)
);

COMMENT ON TABLE Adopt IS '입양';
COMMENT ON COLUMN Adopt.adNumber IS '입양 번호';
COMMENT ON COLUMN Adopt.abNumber IS '유기동물 번호';
COMMENT ON COLUMN Adopt.mNumber IS '회원 번호';
COMMENT ON COLUMN Adopt.residence IS '거주지';
COMMENT ON COLUMN Adopt.maritalStatus IS '결혼 여부';
COMMENT ON COLUMN Adopt.job IS '직업';
COMMENT ON COLUMN Adopt.status IS '처리 상태';

-- 게시판(자유, 문의)
CREATE TABLE BOARD (
	BNUMBER NUMBER NOT NULL,
	MNUMBER NUMBER NOT NULL,
	KINDOFBOARD VARCHAR2(12) DEFAULT '자유' NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	IMGPATH VARCHAR2(300) NULL,
	WRTIME DATE DEFAULT SYSDATE+0.375 NOT NULL,
	CHECKPUBLIC CHAR(1) DEFAULT 'Y' NOT NULL,
	VIEWCOUNT NUMBER DEFAULT 0 NOT NULL,
	REPLYCOUNT NUMBER DEFAULT 0 NOT NULL,
	CONSTRAINT PK_BOARD PRIMARY KEY (BNUMBER)
);

COMMENT ON TABLE Board IS '게시판';
COMMENT ON COLUMN Board.bNumber IS '글 번호';
COMMENT ON COLUMN Board.mNumber IS '회원 번호';
COMMENT ON COLUMN Board.kindOfBoard IS '게시판 종류';
COMMENT ON COLUMN Board.title IS '제목';
COMMENT ON COLUMN Board.content IS '내용';
COMMENT ON COLUMN Board.imgPath IS '사진';
COMMENT ON COLUMN Board.wrTime IS '작성 시간';
COMMENT ON COLUMN Board.checkPublic IS '공개 여부';
COMMENT ON COLUMN Board.viewCount IS '조회수';
COMMENT ON COLUMN Board.replyCount IS '댓글수';


-- 후원
CREATE TABLE DONATION (
	DNUMBER NUMBER NOT NULL,
	ABNUMBER NUMBER NOT NULL,
	MNUMBER NUMBER NOT NULL,
	DONASUM NUMBER NOT NULL,
	BANK VARCHAR2(30) NOT NULL,
	ACCOUNTHOLDER VARCHAR2(100) NOT NULL,
	ACCOUNTNUMBER VARCHAR2(100) NOT NULL,
	CONSTRAINT PK_DONATION PRIMARY KEY (DNUMBER)
);

COMMENT ON TABLE Donation IS '후원';
COMMENT ON COLUMN Donation.dNumber IS '후원 번호';
COMMENT ON COLUMN Donation.abNumber IS '유기동물 번호';
COMMENT ON COLUMN Donation.mNumber IS '회원 번호';
COMMENT ON COLUMN Donation.donaSum IS '후원 금액';
COMMENT ON COLUMN Donation.bank IS '은행';
COMMENT ON COLUMN Donation.accountHolder IS '예금주';
COMMENT ON COLUMN Donation.accountNumber IS '계좌번호';

-- 찾아요 게시판
CREATE TABLE FINDANIMALBOARD (
	FANUMBER NUMBER NOT NULL,
	MNUMBER NUMBER NOT NULL,
	SPECIES VARCHAR2(10) DEFAULT '기타' NOT NULL,
	KIND VARCHAR2(50) NULL,
	LOCATION VARCHAR2(50) NOT NULL,
	ANIMALSTATE VARCHAR2(10) DEFAULT '실종' NOT NULL,
	IMGPATH VARCHAR2(300) DEFAULT 'no_image.png' NOT NULL,
	WRTIME DATE DEFAULT SYSDATE+0.375 NOT NULL,
	TITLE VARCHAR2(60) NOT NULL,
	CONTENT VARCHAR2(1100) NOT NULL,
	VIEWCOUNT NUMBER DEFAULT 0 NOT NULL,
	CONSTRAINT PK_FINDANIMALBOARD PRIMARY KEY (FANUMBER)
);

COMMENT ON TABLE FindAnimalBoard IS '반려동물 찾아요 게시판';
COMMENT ON COLUMN FindAnimalBoard.faNumber IS '글 번호';
COMMENT ON COLUMN FindAnimalBoard.mNumber IS '회원 번호';
COMMENT ON COLUMN FindAnimalBoard.species IS '종';
COMMENT ON COLUMN FindAnimalBoard.kind IS '품종';
COMMENT ON COLUMN FindAnimalBoard.location IS '위치';
COMMENT ON COLUMN FindAnimalBoard.animalState IS '반려동물 상태';
COMMENT ON COLUMN FindAnimalBoard.imgPath IS '사진';
COMMENT ON COLUMN FindAnimalBoard.wrTime IS '작성 시간';
COMMENT ON COLUMN FindAnimalBoard.title IS '제목';
COMMENT ON COLUMN FindAnimalBoard.content IS '내용';
COMMENT ON COLUMN FindAnimalBoard.viewCount IS '조회수';

-- 봤어요 게시판
CREATE TABLE LOOKANIMALBOARD (
	LANUMBER NUMBER NOT NULL,
	MNUMBER NUMBER NOT NULL,
	SPECIES VARCHAR2(10) DEFAULT '기타' NOT NULL,
	KIND VARCHAR2(50) NULL,
	LOCATION VARCHAR2(50) NOT NULL,
	ANIMALSTATE VARCHAR2(10) DEFAULT '보호' NOT NULL,
	IMGPATH VARCHAR2(300) DEFAULT 'no_image.png' NOT NULL,
	WRTIME DATE DEFAULT SYSDATE+0.375 NOT NULL,
	TITLE VARCHAR2(60) NOT NULL,
	CONTENT VARCHAR2(1100) NOT NULL,
	VIEWCOUNT NUMBER DEFAULT 0  NOT NULL,
	CONSTRAINT PK_LOOKANIMALBOARD PRIMARY KEY (LANUMBER)
);

COMMENT ON TABLE LookAnimalBoard IS '유기동물 봤어요 게시판';
COMMENT ON COLUMN LookAnimalBoard.laNumber IS '글 번호';
COMMENT ON COLUMN LookAnimalBoard.mNumber IS '회원 번호';
COMMENT ON COLUMN LookAnimalBoard.species IS '종';
COMMENT ON COLUMN LookAnimalBoard.kind IS '품종';
COMMENT ON COLUMN LookAnimalBoard.location IS '위치';
COMMENT ON COLUMN LookAnimalBoard.animalState IS '유기동물 상태';
COMMENT ON COLUMN LookAnimalBoard.imgPath IS '사진';
COMMENT ON COLUMN LookAnimalBoard.wrTime IS '작성 시간';
COMMENT ON COLUMN LookAnimalBoard.title IS '제목';
COMMENT ON COLUMN LookAnimalBoard.content IS '내용';
COMMENT ON COLUMN LookAnimalBoard.viewCount IS '조회수';

-- 회원
CREATE TABLE MEMBER (
	MNUMBER NUMBER NOT NULL,
	ID VARCHAR2(50) NOT NULL,
	PW VARCHAR2(50) NOT NULL,
	NAME VARCHAR2(50) NOT NULL,
	BIRTH VARCHAR2(50) NOT NULL,
	GENDER CHAR(1) NOT NULL,
	EMAIL VARCHAR2(50) NOT NULL,
	PHONE VARCHAR2(40) NOT NULL,
	GRADE VARCHAR2(10) DEFAULT '일반' NOT NULL,
	CONSTRAINT M_GENDER_CHECK CHECK (gender IN ('M', 'F')),
	CONSTRAINT M_GRADE_CHECK CHECK (grade IN ('일반', '관리자')),
	CONSTRAINT PK_MEMBER PRIMARY KEY (MNUMBER),
	CONSTRAINT M_CK_MNUMBER_NOTNULL CHECK ("MNUMBER" IS NOT NULL),
	CONSTRAINT M_CK_ID_NOTNULL CHECK ("ID" IS NOT NULL),
	CONSTRAINT M_CK_PW_NOTNULL CHECK ("PW" IS NOT NULL),
	CONSTRAINT M_CK_NAME_NOTNULL CHECK ("NAME" IS NOT NULL),
	CONSTRAINT M_CK_BIRTH_NOTNULL CHECK ("BIRTH" IS NOT NULL),
	CONSTRAINT M_CK_GENDER_NOTNULL CHECK ("GENDER" IS NOT NULL),
	CONSTRAINT M_CK_EMAIL_NOTNULL CHECK ("EMAIL" IS NOT NULL),
	CONSTRAINT M_CK_PHONE_NOTNULL CHECK ("PHONE" IS NOT NULL),
	CONSTRAINT M_CK_GRADE_NOTNULL CHECK ("GRADE" IS NOT NULL)
);

COMMENT ON TABLE MEMBER IS '회원';
COMMENT ON COLUMN MEMBER.mNumber IS '회원 번호';
COMMENT ON COLUMN MEMBER.id IS '아이디';
COMMENT ON COLUMN MEMBER.pw IS '비밀번호';
COMMENT ON COLUMN MEMBER.name IS '회원 이름';
COMMENT ON COLUMN MEMBER.birth IS '생년월일';
COMMENT ON COLUMN MEMBER.gender IS '성별';
COMMENT ON COLUMN MEMBER.email IS '이메일';
COMMENT ON COLUMN MEMBER.phone IS '연락처';
COMMENT ON COLUMN MEMBER.grade IS '등급';

-- 보호소
CREATE TABLE SHELTER (
    SNUMBER NUMBER NOT NULL,
    GROUPNAME VARCHAR2(30) NOT NULL,
    LOCATION VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(40) NOT NULL,
    CONSTRAINT PK_SHELTER PRIMARY KEY (SNUMBER),
    CONSTRAINT SYS_C0029968 CHECK ("SNUMBER" IS NOT NULL),
    CONSTRAINT SYS_C0029969 CHECK ("GROUPNAME" IS NOT NULL),
    CONSTRAINT SYS_C0029970 CHECK ("LOCATION" IS NOT NULL),
    CONSTRAINT SYS_C0033921 CHECK ("PHONE" IS NOT NULL)
);

COMMENT ON TABLE Shelter IS '보호소';
COMMENT ON COLUMN Shelter.sNumber IS '보호소 번호';
COMMENT ON COLUMN Shelter.groupName IS '단체명';
COMMENT ON COLUMN Shelter.location IS '지역';
COMMENT ON COLUMN Shelter.phone IS '연락처';

-- 댓글
CREATE TABLE BOARDREPLY (
    BRNUMBER NUMBER NOT NULL,
    BNUMBER NUMBER NOT NULL,
    MNUMBER NUMBER NOT NULL,
    REPLY VARCHAR2(900) NOT NULL,
    WRTIME DATE DEFAULT SYSDATE+0.375 NOT NULL,
    CONSTRAINT PK_BOARDREPLY PRIMARY KEY (BRNUMBER)
);

COMMENT ON TABLE BoardReply IS '게시판 댓글';
COMMENT ON COLUMN BoardReply.brNumber IS '댓글 번호';
COMMENT ON COLUMN BoardReply.bNumber IS '글 번호';
COMMENT ON COLUMN BoardReply.mNumber IS '회원 번호';
COMMENT ON COLUMN BoardReply.reply IS '댓글 내용';
COMMENT ON COLUMN BoardReply.wrTime IS '작성 시간';

-- 임시보호
CREATE TABLE TEMPPET (
	TNUMBER NUMBER NOT NULL,
	ABNUMBER NUMBER NOT NULL,
	MNUMBER NUMBER NOT NULL,
    TEMPDATE DATE DEFAULT SYSDATE+0.375 NOT NULL,
	TEMPPERIOD NUMBER NOT NULL,
	RESIDENCE VARCHAR2(300) NOT NULL,
	MARITALSTATUS VARCHAR2(100) NOT NULL,
	JOB VARCHAR2(100) NOT NULL,
	STATUS VARCHAR2(100) DEFAULT '처리중'  NOT NULL,
	CONSTRAINT PK_TEMPPET PRIMARY KEY (TNUMBER)
);

COMMENT ON TABLE TempPet IS '임시보호';
COMMENT ON COLUMN TempPet.tNumber IS '임시보호 번호';
COMMENT ON COLUMN TempPet.abNumber IS '유기동물 번호';
COMMENT ON COLUMN TempPet.mNumber IS '회원 번호';
COMMENT ON COLUMN TempPet.tempDate IS '임시보호 시작날짜';
COMMENT ON COLUMN TempPet.tempPeriod IS '임시보호 기간';
COMMENT ON COLUMN TempPet.residence IS '거주지';
COMMENT ON COLUMN TempPet.maritalStatus IS '결혼 여부';
COMMENT ON COLUMN TempPet.job IS '직업';
COMMENT ON COLUMN TempPet.status IS '처리 상태';


-- FK
-- cascade 추가
ALTER TABLE Donation
	ADD
		CONSTRAINT FK_AB_TO_D
		FOREIGN KEY (
			abNumber
		)
		REFERENCES AbandonedAnimal (
			abNumber
		)
        ON DELETE CASCADE;

ALTER TABLE Donation
	ADD
		CONSTRAINT FK_M_TO_D
		FOREIGN KEY (
			mNumber
		)
		REFERENCES Member (
			mNumber
		)
		ON DELETE CASCADE;

ALTER TABLE Adopt
	ADD
		CONSTRAINT FK_M_TO_AD
		FOREIGN KEY (
			mNumber
		)
		REFERENCES Member (
			mNumber
		)
		ON DELETE CASCADE;

ALTER TABLE Adopt
	ADD
		CONSTRAINT FK_AB_TO_AD
		FOREIGN KEY (
			abNumber
		)
		REFERENCES AbandonedAnimal (
			abNumber
		)
        ON DELETE CASCADE;

ALTER TABLE TempPet
	ADD
		CONSTRAINT FK_AB_TO_T
		FOREIGN KEY (
			abNumber
		)
		REFERENCES AbandonedAnimal (
			abNumber
		)
        ON DELETE CASCADE;

ALTER TABLE TempPet
	ADD
		CONSTRAINT FK_M_TO_T
		FOREIGN KEY (
			mNumber
		)
		REFERENCES Member (
			mNumber
		)
		ON DELETE CASCADE;

ALTER TABLE AbandonedAnimal
	ADD
		CONSTRAINT FK_S_TO_AB
		FOREIGN KEY (
			sNumber
		)
		REFERENCES Shelter (
			sNumber
		)
        ON DELETE CASCADE;

ALTER TABLE FindAnimalBoard
	ADD
		CONSTRAINT FK_M_TO_FA
		FOREIGN KEY (
			mNumber
		)
		REFERENCES Member (
			mNumber
		)
		ON DELETE CASCADE;

ALTER TABLE LookAnimalBoard
	ADD
		CONSTRAINT FK_M_TO_LA
		FOREIGN KEY (
			mNumber
		)
		REFERENCES Member (
			mNumber
		)
		ON DELETE CASCADE;

ALTER TABLE Board
	ADD
		CONSTRAINT FK_M_TO_B
		FOREIGN KEY (
			mNumber
		)
		REFERENCES Member (
			mNumber
		)
		ON DELETE CASCADE;

ALTER TABLE BoardReply
	ADD
		CONSTRAINT FK_M_TO_BR
		FOREIGN KEY (
			mNumber
		)
		REFERENCES Member (
			mNumber
		)
		ON DELETE CASCADE;

ALTER TABLE BoardReply
	ADD
		CONSTRAINT FK_B_TO_BR
		FOREIGN KEY (
			bNumber
		)
		REFERENCES Board (
			bNumber
		)
		ON DELETE CASCADE;


-- SEQUENCE 생성
CREATE SEQUENCE M_NUMBER_SEQ
INCREMENT BY 1
START WITH 0
MINVALUE 0
NOCYCLE;

CREATE SEQUENCE AB_NUMBER_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOCYCLE;

CREATE SEQUENCE AD_NUMBER_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOCYCLE;

CREATE SEQUENCE T_NUMBER_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOCYCLE;

CREATE SEQUENCE D_NUMBER_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOCYCLE;

CREATE SEQUENCE S_NUMBER_SEQ
INCREMENT BY 1
START WITH 0
MINVALUE 0
NOCYCLE;

CREATE SEQUENCE FA_NUMBER_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOCYCLE;

CREATE SEQUENCE LA_NUMBER_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOCYCLE;

CREATE SEQUENCE B_NUMBER_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOCYCLE;

CREATE SEQUENCE BR_NUMBER_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOCYCLE;



-- TRIGGER 생성(각 번호 자동 증가)
CREATE OR REPLACE TRIGGER M_INSERT_TRIGGER
BEFORE
INSERT ON Member
FOR EACH ROW
BEGIN
    SELECT M_NUMBER_SEQ.NEXTVAL INTO :new.mNumber FROM DUAL;
END;

CREATE OR REPLACE TRIGGER AB_INSERT_TRIGGER
BEFORE
INSERT ON AbandonedAnimal
FOR EACH ROW
BEGIN
    SELECT AB_NUMBER_SEQ.NEXTVAL INTO :new.abNumber FROM DUAL;
END;

CREATE OR REPLACE TRIGGER AD_INSERT_TRIGGER
BEFORE
INSERT ON Adopt
FOR EACH ROW
BEGIN
    SELECT AD_NUMBER_SEQ.NEXTVAL INTO :new.adNumber FROM DUAL;
END;

CREATE OR REPLACE TRIGGER T_INSERT_TRIGGER
BEFORE
INSERT ON TempPet
FOR EACH ROW
BEGIN
    SELECT T_NUMBER_SEQ.NEXTVAL INTO :new.tNumber FROM DUAL;
END;

CREATE OR REPLACE TRIGGER D_INSERT_TRIGGER
BEFORE
INSERT ON Donation
FOR EACH ROW
BEGIN
    SELECT D_NUMBER_SEQ.NEXTVAL INTO :new.dNumber FROM DUAL;
END;

CREATE OR REPLACE TRIGGER S_INSERT_TRIGGER
BEFORE
INSERT ON Shelter
FOR EACH ROW
BEGIN
    SELECT S_NUMBER_SEQ.NEXTVAL INTO :new.sNumber FROM DUAL;
END;

CREATE OR REPLACE TRIGGER FA_INSERT_TRIGGER
BEFORE
INSERT ON FindAnimalBoard
FOR EACH ROW
BEGIN
    SELECT FA_NUMBER_SEQ.NEXTVAL INTO :new.faNumber FROM DUAL;
END;

CREATE OR REPLACE TRIGGER LA_INSERT_TRIGGER
BEFORE
INSERT ON LookAnimalBoard
FOR EACH ROW
BEGIN
    SELECT LA_NUMBER_SEQ.NEXTVAL INTO :new.laNumber FROM DUAL;
END;

CREATE OR REPLACE TRIGGER B_INSERT_TRIGGER
BEFORE
INSERT ON Board
FOR EACH ROW
BEGIN
    SELECT B_NUMBER_SEQ.NEXTVAL INTO :new.bNumber FROM DUAL;
END;

CREATE OR REPLACE TRIGGER BR_INSERT_TRIGGER
BEFORE
INSERT ON BoardReply
FOR EACH ROW
BEGIN
    SELECT BR_NUMBER_SEQ.NEXTVAL INTO :new.brNumber FROM DUAL;
END;



-- DML 예시 데이터 추가
-- 시간 넣고싶으면 TO_DATE('2023-01-01 00:00', 'YYYY-MM-DD HH24:MI') 형식으로

-- MEMBER INSERT
INSERT INTO MEMBER (ID, PW, NAME, BIRTH, GENDER, EMAIL, PHONE, GRADE)
VALUES ('admin', 'admin', 'admin', '2023-01-01', 'M', 'admin@petmily.com', '01000000000', '관리자');
INSERT INTO MEMBER (ID, PW, NAME, BIRTH, GENDER, EMAIL, PHONE)
VALUES ('petmily1', 'petmily123!','베들링턴boy','1995-01-09', 'M', 'pet1@petmily.com', '01000000001');
INSERT INTO MEMBER (ID, PW, NAME, BIRTH, GENDER, EMAIL, PHONE)
VALUES ('petmily2', 'petmily123!','괴발자','2000-10-07', 'F', 'pet2@petmily.com', '01000000002');
INSERT INTO MEMBER (ID, PW, NAME, BIRTH, GENDER, EMAIL, PHONE)
VALUES ('petmily3', 'petmily123!','개발새발','2004-05-25', 'M', 'pet3@petmily.com', '01000000003');
INSERT INTO MEMBER (ID, PW, NAME, BIRTH, GENDER, EMAIL, PHONE)
VALUES ('petmily4', 'petmily123!','귀요미비숑','1995-07-16', 'F', 'pet4@petmily.com', '01000000004');
INSERT INTO MEMBER (ID, PW, NAME, BIRTH, GENDER, EMAIL, PHONE)
VALUES ('petmily5', 'petmily123!','밤숭이','1998-11-14', 'M', 'pet5@petmily.com', '01000000005');
INSERT INTO MEMBER (ID, PW, NAME, BIRTH, GENDER, EMAIL, PHONE)
VALUES ('petmily6', 'petmily123!','군밤숭','2001-09-21', 'F', 'pet6@petmily.com', '01000000006');


-- SHELTER INSERT
INSERT INTO SHELTER (GROUPNAME, LOCATION, PHONE)
VALUES ('입양/임보중', '-', '-');
INSERT INTO SHELTER (GROUPNAME, LOCATION, PHONE)
VALUES ('하늘 보호소', '강남', '01011111111');
INSERT INTO SHELTER (GROUPNAME, LOCATION, PHONE)
VALUES ('무지개 보호소', '강북', '01022222222');
INSERT INTO SHELTER (GROUPNAME, LOCATION, PHONE)
VALUES ('행복 보호소', '강서', '01033333333');
INSERT INTO SHELTER (GROUPNAME, LOCATION, PHONE)
VALUES ('햇살 보호소', '김포', '01044444444');
INSERT INTO SHELTER (GROUPNAME, LOCATION, PHONE)
VALUES ('사랑가득 보호소', '인천', '01044444444');


-- ABANDONEDANIMAL INSERT
--보호
INSERT INTO ABANDONEDANIMAL (SNUMBER, NAME, SPECIES, KIND, GENDER, AGE, WEIGHT, IMGPATH, LOCATION, ADMISSIONDATE, UNIQUENESS, DESCRIPTION)
VALUES (1,'코코','개','말티즈','F',3,5.2,'maltese.jpg','서초','2023-01-22','건강하고 튼튼함, 즉시 입양 가능','사람을 잘 따릅니다. 코코의 가족을 찾고 있어요');
INSERT INTO ABANDONEDANIMAL (SNUMBER, NAME, SPECIES, KIND, GENDER, AGE, WEIGHT, IMGPATH, LOCATION, ADMISSIONDATE, UNIQUENESS, DESCRIPTION)
VALUES (2,'보리','기타','햄스터','M',3,1.5,'hamster.jpg','강남','2023-02-05','활동적인 편이나 식탐이 많음','사랑으로 보듬어줄 가족을 찾고 있어요');
INSERT INTO ABANDONEDANIMAL (SNUMBER, NAME, SPECIES, KIND, GENDER, AGE, WEIGHT, IMGPATH, LOCATION, ADMISSIONDATE, UNIQUENESS, DESCRIPTION)
VALUES (3,'푸딩','개','토이푸들','M',2,2.3,'toypoodle.jpg','구룡','2023-02-08','낯을 가림. 몸이 허약한 편','몸이 허약한 편이라 사랑으로 보듬어줄 가족이 필요합니다');
INSERT INTO ABANDONEDANIMAL (SNUMBER, NAME, SPECIES, KIND, GENDER, AGE, WEIGHT, IMGPATH, LOCATION, ADMISSIONDATE, UNIQUENESS, DESCRIPTION)
VALUES (4,'노랑','고양이','페르시안','F',4,7,'persian.jpg','개포','2023-04-17','독립적인 성향임','독립적인 편이라 동반자로 함께 살아갈 가족을 찾고 있어요');
INSERT INTO ABANDONEDANIMAL (SNUMBER, NAME, SPECIES, KIND, GENDER, AGE, WEIGHT, IMGPATH, LOCATION, ADMISSIONDATE, UNIQUENESS, DESCRIPTION)
VALUES (1,'사랑이','개','베들링턴 테리어','F',3,12.1,'bedlington.jpg','개봉','2023-05-21','초반엔 경계심이 강함','초반엔 경계심이 강하지만 사랑으로 보듬어줄 가족을 찾고 있어요');
INSERT INTO ABANDONEDANIMAL (SNUMBER, NAME, SPECIES, KIND, GENDER, AGE, WEIGHT, IMGPATH, LOCATION, ADMISSIONDATE, UNIQUENESS, DESCRIPTION)
VALUES (1,'호두','고양이','코숏','F',3,5.7,'cat_mix.jpg','사당','2023-07-22','사람을 좋아함','사람을 좋아하는 아이입니다. 사랑으로 보듬어줄 가족을 찾고 있어요');
INSERT INTO ABANDONEDANIMAL (SNUMBER, NAME, SPECIES, KIND, GENDER, AGE, WEIGHT, IMGPATH, LOCATION, ADMISSIONDATE, UNIQUENESS, DESCRIPTION)
VALUES (1,'까미','개','포메라니안','M',2,4.9,'pome.jpg','미금','2023-10-02','낯선 이에겐 포악한 편이라 물리지 않게 조심해야 함','전 주인에게 상처가 많아 사랑으로 보듬어주세요.');
INSERT INTO ABANDONEDANIMAL (SNUMBER, NAME, SPECIES, KIND, GENDER, AGE, WEIGHT, IMGPATH, LOCATION, ADMISSIONDATE, UNIQUENESS, DESCRIPTION)
VALUES (1,'몽이','개','비숑','M',2,5.5,'bichon.jpg','신촌','2023-10-19','건강하고 애교가 많음','활발한 아이입니다. 사랑으로 보듬어 줄 가족을 찾고 있어요.');

--임보
INSERT INTO ABANDONEDANIMAL (SNUMBER, NAME, SPECIES, KIND, GENDER, AGE, WEIGHT, IMGPATH, LOCATION, ADMISSIONDATE, UNIQUENESS, DESCRIPTION, ANIMALSTATE)
VALUES (0,'초코','고양이','코숏','M',3,5.6,'cat_mix.jpg','노원','2023-06-15','초면엔 경계심이 많음','아픔이 있는 아이를 사랑으로 보듬어줄 가족을 찾고 있어요', '임보');
INSERT INTO ABANDONEDANIMAL (SNUMBER, NAME, SPECIES, KIND, GENDER, AGE, WEIGHT, IMGPATH, LOCATION, ADMISSIONDATE, UNIQUENESS, DESCRIPTION, ANIMALSTATE)
VALUES (0,'콩이','기타','코알라','M',3,8.2,'koala.jpg','마포','2023-07-11','사람을 좋아하고 애교가 많음','아픔이 있는 아이를 사랑으로 보듬어줄 가족을 찾고 있어요', '임보');

--입양
INSERT INTO ABANDONEDANIMAL (SNUMBER, NAME, SPECIES, KIND, GENDER, AGE, WEIGHT, IMGPATH, LOCATION, ADMISSIONDATE, UNIQUENESS, DESCRIPTION, ANIMALSTATE)
VALUES (0,'망고','기타','수달','M',1,2.2,'otter.jpg','광교','2023-02-21','건강하지만 사람을 무서워함','아픔이 있는 아이를 사랑으로 보듬어줄 가족을 찾고 있어요', '입양');
INSERT INTO ABANDONEDANIMAL (SNUMBER, NAME, SPECIES, KIND, GENDER, AGE, WEIGHT, IMGPATH, LOCATION, ADMISSIONDATE, UNIQUENESS, DESCRIPTION, ANIMALSTATE)
VALUES (0,'별이','개','포메라니안','M',1,2.2,'pome.jpg','인천','2023-3-27','건강하지만 사람을 무서워함','아픔이 있는 아이를 사랑으로 보듬어줄 가족을 찾고 있어요', '입양');


-- TEMPPET INSERT
INSERT INTO TEMPPET (ABNUMBER, MNUMBER, TEMPPERIOD, RESIDENCE, MARITALSTATUS, JOB, STATUS)
VALUES (5, 3, 3, '경기도', 'married', '유치원교사', '처리중');
INSERT INTO TEMPPET (ABNUMBER, MNUMBER, TEMPPERIOD, RESIDENCE, MARITALSTATUS, JOB, STATUS)
VALUES (6, 4, 4, '서울특별시', 'single', '연극배우', '처리중');

INSERT INTO TEMPPET (ABNUMBER, MNUMBER, TEMPPERIOD, RESIDENCE, MARITALSTATUS, JOB, STATUS)
VALUES (1, 5, 3, '강원도', 'married', '네트워크 엔지니어', '거절');
INSERT INTO TEMPPET (ABNUMBER, MNUMBER, TEMPPERIOD, RESIDENCE, MARITALSTATUS, JOB, STATUS)
VALUES (2, 6, 2, '서울특별시', 'single', '의사', '거절');

INSERT INTO TEMPPET (ABNUMBER, MNUMBER, TEMPPERIOD, RESIDENCE, MARITALSTATUS, JOB, STATUS)
VALUES (9, 1, 2, '충청북도', 'single', '디자이너', '완료');
INSERT INTO TEMPPET (ABNUMBER, MNUMBER, TEMPPERIOD, RESIDENCE, MARITALSTATUS, JOB, STATUS)
VALUES (10, 2, 3, '서울특별시', 'married', '기획자', '완료');


-- ADOPT INSERT
INSERT INTO ADOPT (ABNUMBER, MNUMBER, RESIDENCE, MARITALSTATUS, JOB, STATUS)
VALUES (7, 5, '전라남도', 'single', '택시기사', '처리중');
INSERT INTO ADOPT (ABNUMBER, MNUMBER, RESIDENCE, MARITALSTATUS, JOB, STATUS)
VALUES (8, 6, '제주특별자치도', 'married', '버스기사', '처리중');

INSERT INTO ADOPT (ABNUMBER, MNUMBER, RESIDENCE, MARITALSTATUS, JOB, STATUS)
VALUES (3, 3, '충청남도', 'single', '자영업', '거절');
INSERT INTO ADOPT (ABNUMBER, MNUMBER, RESIDENCE, MARITALSTATUS, JOB, STATUS)
VALUES (4, 4, '인천광역시', 'married', '호텔리어', '거절');

INSERT INTO ADOPT (ABNUMBER, MNUMBER, RESIDENCE, MARITALSTATUS, JOB, STATUS)
VALUES (11, 3, '경기도', 'single', '요양보호사', '완료');
INSERT INTO ADOPT (ABNUMBER, MNUMBER, RESIDENCE, MARITALSTATUS, JOB, STATUS)
VALUES (12, 4, '서울특별시', 'married', '요리사', '완료');


-- FINDANIMALBOARD INSERT
INSERT INTO FINDANIMALBOARD (MNUMBER, SPECIES, KIND, LOCATION, IMGPATH, TITLE, CONTENT)
VALUES (1, '개', '불독', '구로', 'bulldog.jpg', '불독을 잃어버렸습니다ㅠㅠ!', '구로에서 산책 중 잠시 한눈 판 사이 저희 집 아이가 사라졌습니다ㅠㅠ');
INSERT INTO FINDANIMALBOARD (MNUMBER, SPECIES, KIND, LOCATION, IMGPATH, TITLE, CONTENT)
VALUES (2, '개', '비숑', '금천', 'bichon.jpg', '비숑을 잃어버렸습니다ㅠㅠ!', '금천에서 산책 중 잠시 한눈 판 사이 저희 집 아이가 사라졌습니다ㅠㅠ');
INSERT INTO FINDANIMALBOARD (MNUMBER, SPECIES, KIND, LOCATION, IMGPATH, TITLE, CONTENT)
VALUES (3, '고양이', '코숏', '양재', 'cat_mix.jpg', '고양이를 잃어버렸습니다ㅠㅠ!', '양재천에서 산책 중 잠시 한눈 판 사이 저희 집 아이가 사라졌습니다ㅠㅠ');
INSERT INTO FINDANIMALBOARD (MNUMBER, SPECIES, KIND, LOCATION, IMGPATH, TITLE, CONTENT)
VALUES (4, '고양이', '먼치킨', '미아', 'cat_chicken.jpg', '저희집 고양이을 잃어버렸습니다ㅠㅠ!', '미아에서 산책 중 잠시 한눈 판 사이 저희 집 아이가 사라졌습니다ㅠㅠ');


-- LOOKANIMALBOARD INSERT
INSERT INTO LOOKANIMALBOARD (MNUMBER, SPECIES, KIND, LOCATION, IMGPATH, TITLE, CONTENT)
VALUES (1, '기타', '도마뱀', '길음', 'lizard.jpg', '도마뱀 잃어버리신분~!! (길음역)', '길음역 부근에서 발견해서 보호중입니다~');
INSERT INTO LOOKANIMALBOARD (MNUMBER, SPECIES, KIND, LOCATION, IMGPATH, TITLE, CONTENT)
VALUES (2, '개', '말티즈', '수유', 'maltese.jpg', '말티즈 보호중입니다!', '수유역 부근에서 발견해서 보호중입니다~');
INSERT INTO LOOKANIMALBOARD (MNUMBER, SPECIES, KIND, LOCATION, IMGPATH, TITLE, CONTENT)
VALUES (3, '개', '진돗개', '역삼', 'jindo.jpg', '역삼에서 진돗개를 발견해 데리고 있습니다', '역삼 부근에서 발견해서 보호중입니다~');
INSERT INTO LOOKANIMALBOARD (MNUMBER, SPECIES, KIND, LOCATION, IMGPATH, TITLE, CONTENT)
VALUES (4, '고양이', '아메리칸컬', '언주', 'cat_curl.jpg', '언주역에서 고양이 잃어버리신분 있나요?', '언주역 부근에서 발견해서 보호중입니다~');


-- FIND, LOOK 매칭
INSERT INTO FINDANIMALBOARD (MNUMBER, SPECIES, KIND, LOCATION, ANIMALSTATE, IMGPATH, TITLE, CONTENT)
VALUES (1, '개', '비숑', '종각', '매칭됨', 'bichon.jpg', '비숑을 잃어버렸습니다ㅠㅠ!', '종각에서 산책 중 잠시 한눈 판 사이 저희 집 아이가 사라졌습니다ㅠㅠ');
INSERT INTO LOOKANIMALBOARD (MNUMBER, SPECIES, KIND, LOCATION, ANIMALSTATE, IMGPATH, TITLE, CONTENT)
VALUES (2, '개', '비숑', '종각', '매칭됨', 'bichon.jpg', '강아지 비숑을 보호중입니다!', '종각에서 산책 중 발견해 보호중입니다. 주인 분은 연락주세요!');

INSERT INTO FINDANIMALBOARD (MNUMBER, SPECIES, KIND, LOCATION, ANIMALSTATE, IMGPATH, TITLE, CONTENT)
VALUES (3, '개', '말티즈', '회현', '매칭됨', 'maltese.jpg', '말티즈를 잃어버렸습니다ㅠㅠ!', '회현에서 산책 중 잠시 한눈 판 사이 저희 집 강아지가 사라졌습니다ㅠㅠ');
INSERT INTO LOOKANIMALBOARD (MNUMBER, SPECIES, KIND, LOCATION, ANIMALSTATE, IMGPATH, TITLE, CONTENT)
VALUES (4, '개', '말티즈', '회현', '매칭됨', 'maltese.jpg', '말티즈를 발견해 보호중입니다!', '회현에서 산책 중 발견해 보호중입니다. 주인 분은 연락주세요!');

INSERT INTO FINDANIMALBOARD (MNUMBER, SPECIES, KIND, LOCATION, ANIMALSTATE, IMGPATH, TITLE, CONTENT)
VALUES (5, '고양이', '러시안블루', '왕십리', '매칭됨', 'russian_blue.jpg', '러시안블루 고양이를 잃어버렸습니다ㅠ', '왕십리에서 산책 중 잠시 한눈 판 사이 저희 집 고양이가 사라졌습니다ㅠㅠ');
INSERT INTO LOOKANIMALBOARD (MNUMBER, SPECIES, KIND, LOCATION, ANIMALSTATE, IMGPATH, TITLE, CONTENT)
VALUES (6, '고양이', '러시안블루', '왕십리', '매칭됨', 'russian_blue.jpg', '러시안블루 고양이를 보호중입니다!', '왕십리에서 발견해 보호중입니다. 주인 분은 연락주세요!');


-- BOARD INSERT
-- 자유
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT)
VALUES (1, '자유', '좋은하루 되세요~', '저도 좋은하루 될게요~');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT)
VALUES (2, '자유', '오늘 하루 어떠셨나요?', '저는 좋았어요 ㅋㅋ');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT)
VALUES (3, '자유', '입양 후 느낀 현실적인 후기 들려주실 분 계실까요?', '실 후기가 궁금합니다 ㅠㅠ');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT)
VALUES (4, '자유', '강아지는 베들링턴 테리어가 귀여운것 같아요~', '특히 옆으로 눌려있는 듯한 좁고 긴 머리가 매력적이에요!');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT)
VALUES (5, '자유', '피곤하네요 ㅠㅠ', '자고싶어요!');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT)
VALUES (6, '자유', '개발이 너무 즐거워요 ㅎㅎ', '전 born to be developer인가봐요~');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT)
VALUES (1, '자유', '아랫분 저도 개발잔데 부럽네요', '저도 개발이 즐거웠으면 좋겠어요~');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT)
VALUES (2, '자유', '오늘 저녁 뭐먹을까요?', '저녁 추천좀 해주세요 :)');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT)
VALUES (3, '자유', '귀뚜라미 소리가 좋네요', '역시 산속에 들어와 살길 잘했어요~ 와이파이는 필수~');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT)
VALUES (4, '자유', '여행가고 싶네요ㅎㅎㅎ', '좋아하는 여행지 있으신가요?');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT)
VALUES (5, '자유', '날씨가 쌀쌀해지네요 ㅠ', '다들 감기 조심하세요 :)');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT)
VALUES (6, '자유', '새해 복 많이 받으세요~', '항상 감사합니다:)');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT)
VALUES (1, '자유', '보통 다들 몇시간쯤 주무시나요?', '전 요즘 하루에 1시간씩만 자도 충분하더라구요~ :)');


-- 문의
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT, CHECKPUBLIC)
VALUES (1, '문의', '문의드립니다!', '입양 절차는 어떻게 되나요?', 'N');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT)
VALUES (2, '문의', '수고하십니다. 문의드릴게 있어서요~', '매칭 결과는 언제쯤 나올까요?');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT)
VALUES (3, '문의', '문의드립니다!', '입양 거절 사유가 있나요?');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT)
VALUES (4, '문의', '궁금한점 있습니다.', '임시보호 기간이 최소 1개월인 이유가 무엇인가요?');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT, CHECKPUBLIC)
VALUES (5, '문의', '문의드려요', '임시보호 거절 기준은 어떻게되나요?', 'N');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT)
VALUES (6, '문의', '문의드립니다!', '보호소에 따로 후원을 할 수 있는 방법은 없나요?');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT)
VALUES (1, '문의', '파양 관련해서 문의드립니다ㅠ', '혹시 파양을 하게되면 받아주시나요?');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT)
VALUES (2, '문의', '문의드립니다!', '봉사하고 싶은데 방법을 모르겠어요');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT)
VALUES (3, '문의', '안녕하세요~ 문의드립니다!', '팻밀리는 봉사 단체인건가요?');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT, CHECKPUBLIC)
VALUES (4, '문의', '궁금한 점 질문있습니다~', '입양한지 얼마 안됐는데 한마리 더 입양 가능할까요?', 'N');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT)
VALUES (5, '문의', '안녕하세요 문의드립니다!', '최대 동시에 임시보호 가능한 마릿수가 어떻게 되나요?');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT)
VALUES (6, '문의', '궁금한 사항이 있습니다~', '서울에 있는 보호소 지역을 알려주세요.');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT)
VALUES (1, '문의', '문의드립니다!', '임시보호 중입니다. 간식은 하루에 최대 몇번까지 줘도 되나요?');


-- 입양후기
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT, IMGPATH)
VALUES (3, '입양후기', '최고로 귀여운 수달, 우리 망고를 소개합니다~', '우리 망고에요. 집에서 헤엄도 잘칩니다. 이쁘게 키울게요. 사랑해 망고야!!', 'otter.jpg');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT, IMGPATH)
VALUES (4, '입양후기', '저희 가족이 된 별이를 소개해드릴게요', '처음엔 낯을 많이 가려 걱정했는데, 매일매일 애교가 넘치는 별이 덕분에 가정의 분위기도 화기애애해졌답니다~', 'pome.jpg');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT, IMGPATH)
VALUES (0, '입양후기', '우리 수박이를 소개합니다~', '저희 수박이 이쁘게 키울게요. 사랑해 수박아!!', 'bedlington.jpg');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT, IMGPATH)
VALUES (0, '입양후기', '저희 참외를 소개할게요!', '저희 참외 이쁘게 키울게요. 사랑해 참외야!!', 'hamster.jpg');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT, IMGPATH)
VALUES (0, '입양후기', '우리 홍시를 입양하게 되서 너무 기뻐요', '저희 홍시 이쁘게 키울게요. 사랑해 홍시야!!', 'persian.jpg');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT, IMGPATH)
VALUES (0, '입양후기', '저희 곶감이를 소개합니다~', '저희 곶감이 이쁘게 키울게요. 사랑해 곶감아!!', 'toypoodle.jpg');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT, IMGPATH)
VALUES (0, '입양후기', '우리 머스캣을 소개합니다~', '저희 머스캣 이쁘게 키울게요. 사랑해 머스캣!!', 'jindo.jpg');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT, IMGPATH)
VALUES (0, '입양후기', '저희 리자드를 소개합니다~', '저희 자드 이쁘게 키울게요. 사랑해 리자드!!', 'lizard.jpg');
INSERT INTO BOARD (MNUMBER, KINDOFBOARD, TITLE, CONTENT, IMGPATH)
VALUES (0, '입양후기', '우리 블랙이를 소개합니다~', '저희 블랙이 이쁘게 키울게요. 사랑해 석블랙!!', 'russian_blue.jpg');


-- 후원
INSERT INTO DONATION (ABNUMBER, MNUMBER, DONASUM, BANK, ACCOUNTHOLDER, ACCOUNTNUMBER)
VALUES (1, 1, 30000, '카카오뱅크', '김지훈', '3333-19-1111111');
INSERT INTO DONATION (ABNUMBER, MNUMBER, DONASUM, BANK, ACCOUNTHOLDER, ACCOUNTNUMBER)
VALUES (2, 3, 100000, 'KEB하나은행', '김석훈', '015-512-5161222');
INSERT INTO DONATION (ABNUMBER, MNUMBER, DONASUM, BANK, ACCOUNTHOLDER, ACCOUNTNUMBER)
VALUES (2, 3, 10000, 'IBK기업은행', '김지석', '3331-51-215142');

COMMIT;