-- DROP TRIGGER
DROP TRIGGER M_INSERT_TRIGGER;
DROP TRIGGER AB_INSERT_TRIGGER;
DROP TRIGGER AD_INSERT_TRIGGER;
DROP TRIGGER T_INSERT_TRIGGER;
DROP TRIGGER D_INSERT_TRIGGER;
DROP TRIGGER S_INSERT_TRIGGER;
DROP TRIGGER FA_INSERT_TRIGGER;
DROP TRIGGER LA_INSERT_TRIGGER;
DROP TRIGGER B_INSERT_TRIGGER;
DROP TRIGGER BR_INSERT_TRIGGER;

-- DROP SEQUENCE
DROP SEQUENCE M_NUMBER_SEQ;
DROP SEQUENCE AB_NUMBER_SEQ;
DROP SEQUENCE AD_NUMBER_SEQ;
DROP SEQUENCE T_NUMBER_SEQ;
DROP SEQUENCE D_NUMBER_SEQ;
DROP SEQUENCE S_NUMBER_SEQ;
DROP SEQUENCE FA_NUMBER_SEQ;
DROP SEQUENCE LA_NUMBER_SEQ;
DROP SEQUENCE B_NUMBER_SEQ;
DROP SEQUENCE BR_NUMBER_SEQ;

-- DROP CONSTRAINT
ALTER TABLE Donation DROP CONSTRAINT FK_AB_TO_D;
ALTER TABLE Donation DROP CONSTRAINT FK_M_TO_D;

ALTER TABLE Adopt DROP CONSTRAINT FK_AB_TO_AD;
ALTER TABLE Adopt DROP CONSTRAINT FK_M_TO_AD;

ALTER TABLE TempPet DROP CONSTRAINT FK_AB_TO_T;
ALTER TABLE TempPet DROP CONSTRAINT FK_M_TO_T;

ALTER TABLE AbandonedAnimal DROP CONSTRAINT FK_S_TO_AB;
ALTER TABLE FindAnimalBoard DROP CONSTRAINT FK_M_TO_FA;
ALTER TABLE LookAnimalBoard DROP CONSTRAINT FK_M_TO_LA;

ALTER TABLE Board DROP CONSTRAINT FK_M_TO_B;
ALTER TABLE BoardReply DROP CONSTRAINT FK_M_TO_BR;
ALTER TABLE BoardReply DROP CONSTRAINT FK_B_TO_BR;

-- DROP TABLE
DROP TABLE SHELTER CASCADE constraints;
DROP TABLE ABANDONEDANIMAL CASCADE constraints;
DROP TABLE ADOPT CASCADE constraints;
DROP TABLE BOARD CASCADE constraints;
DROP TABLE BOARDREPLY CASCADE constraints;
DROP TABLE DONATION CASCADE constraints;
DROP TABLE FINDANIMALBOARD CASCADE constraints;
DROP TABLE LOOKANIMALBOARD CASCADE constraints;
DROP TABLE MEMBER CASCADE constraints;
DROP TABLE TEMPPET CASCADE constraints;